#!/bin/bash
set -e
DEFAULT_VERSION=0.90.0.RC1
if [ "$SERVICE_VERSION" ]
then
    VERSION=$SERVICE_VERSION
else
    VERSION=$DEFAULT_VERSION
fi

cd "$(dirname "$0")"
if [ -d ~/elasticsearch-$VERSION ]
then
    echo "Elastic search seems to be already installed."
else
    echo "Installing ElasticSearch (version $VERSION)..."
    curl -L http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$VERSION.tar.gz |
        tar -C ~ -zxf-

    echo "Setting up dotCloud scaffolding..."
    ln -s elasticsearch-$VERSION ~/elasticsearch
    
    echo "Installing elasticsearch-head Plugin..."
    elasticsearch/bin/plugin -install mobz/elasticsearch-head

    echo "Installing Elasticsearch Jetty Plugin..."
    elasticsearch/bin/plugin -url https://oss-es-plugins.s3.amazonaws.com/elasticsearch-jetty/elasticsearch-jetty-0.20.1.zip -install elasticsearch-jetty-0.20.1
    cp run ~
fi
